import { v4 as uuidv4 } from 'uuid'
export const data = [
  {
    id: uuidv4(),
    url: 'src/assets/expresso.png',
    title: 'Expresso Tradicional',
    description: 'Expresso diluído, menos intenso que o tradicional',
    tag: ['Tradicional'],
    valor: 9.9,
  },
  {
    id: uuidv4(),
    url: 'src/assets/expressoCremoso.png',
    title: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    tag: ['Tradicional'],
    valor: 12.5,
  },

  {
    id: uuidv4(),
    url: 'src/assets/cafeGelado.png',
    title: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    tag: ['tradicional', 'gelado'],
    valor: 8.5,
  },
  {
    id: uuidv4(),
    url: 'src/assets/arabe.png',
    title: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    tag: ['Especial'],
    valor: 18.9,
  },
  {
    id: uuidv4(),
    url: 'src/assets/cafeLeite.png',
    title: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    tag: ['Tradicional', 'com leite'],
    valor: 16.9,
  },
  {
    id: uuidv4(),
    url: 'src/assets/latte.png',
    title: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    tag: ['Tradicional', 'com leite'],
    valor: 15.9,
  },
  {
    id: uuidv4(),
    url: 'src/assets/capuccino.png',
    title: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    tag: ['Tradicional', 'com leite'],
    valor: 13.9,
  },
  {
    id: uuidv4(),
    url: 'src/assets/cafemochiato.png',
    title: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    tag: ['Tradicional', 'com leite'],
    valor: 12.5,
  },
  {
    id: uuidv4(),
    url: 'src/assets/mochaccino.png',
    title: 'Macchiato',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    tag: ['Tradicional', 'com leite'],
    valor: 21.9,
  },
  {
    id: uuidv4(),
    url: 'src/assets/chocolateQuente.png',
    title: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    tag: ['Tradicional', 'com leite'],
    valor: 18.9,
  },
  {
    id: uuidv4(),
    url: 'src/assets/cubano.png',
    title: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    tag: ['Especial', 'alcoólico', 'gelado'],
    valor: 25.9,
  },
  {
    id: uuidv4(),
    url: 'src/assets/havaiano.png',
    title: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    tag: ['Especial'],
    valor: 24.9,
  },
  {
    id: uuidv4(),
    url: 'src/assets/irlandes.png',
    title: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    tag: ['Especial', 'alcoólico'],
    valor: 12.5,
  },
  {
    id: uuidv4(),
    url: 'src/assets/americano.png',
    title: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    tag: ['tradicional'],
    valor: 9.9,
  },
]
